name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: website/package-lock.json
          node-version: 18
          cache: npm

      - name: Install Cargo
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Create API docs
        run: cargo run --release
        working-directory: website-generator
      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build